hmrc/tax-history

app/uk/gov/hmrc/taxhistory/connectors/BaseConnector.scala
app/uk/gov/hmrc/taxhistory/connectors/des/RtiConnector.scala
test/uk/gov/hmrc/taxhistory/connectors/RtiConnectorSpec.scala

rather than a specific object.

AFID-4 refactored connector to return HttpResponse

---

app/uk/gov/hmrc/taxhistory/model/taxhistory/Employment.scala
test/uk/gov/hmrc/taxhistory/model/rti/RtiDataSpec.scala

and also removed come comments from RtiDataSpec

AFID-21 created model to be used between frontend and backend

---

app/uk/gov/hmrc/taxhistory/controllers/AuthController.scala
app/uk/gov/hmrc/taxhistory/controllers/IndividualTaxYearController.scala
app/uk/gov/hmrc/taxhistory/controllers/TaxHistoryController.scala
app/uk/gov/hmrc/taxhistory/utils/TaxHistoryLogger.scala
conf/logback.xml

-Added appropriate loggers.
-Some changes in logback.xml to match the front end.

[AFID-273] - Review error handling and logging - Backend

---

app/uk/gov/hmrc/taxhistory/connectors/BaseConnector.scala
app/uk/gov/hmrc/taxhistory/connectors/nps/NpsConnector.scala
app/uk/gov/hmrc/taxhistory/services/EmploymentHistoryService.scala
app/uk/gov/hmrc/taxhistory/services/helpers/IabdsHelper.scala
app/uk/gov/hmrc/taxhistory/services/helpers/RtiDataHelper.scala

updated the original Loggers to implement the TaxHistoryLogger instead

[AFID-273]Review error handling and logging - Backend

---

test/uk/gov/hmrc/taxhistory/services/AllowancesServiceSpec.scala
test/uk/gov/hmrc/taxhistory/services/EmploymentServiceSpec.scala
test/uk/gov/hmrc/taxhistory/services/IabdsHelperSpec.scala
test/uk/gov/hmrc/taxhistory/services/PayAndTaxServiceSpec.scala
test/uk/gov/hmrc/taxhistory/services/TaxAccountServiceSpec.scala
test/uk/gov/hmrc/taxhistory/services/helper/EmploymentHistoryServiceHelperSpec.scala

[AFID-319] rewrote json as scala objects for tests

[AFID-319] Replace JSON defined in tests with Scala objects

---

app/Module.scala
app/uk/gov/hmrc/taxhistory/connectors/NpsConnector.scala
app/uk/gov/hmrc/taxhistory/connectors/RtiConnector.scala
conf/application.conf
test/uk/gov/hmrc/taxhistory/connectors/NpsConnectorSpec.scala
test/uk/gov/hmrc/taxhistory/connectors/RtiConnectorSpec.scala

Removed unused path config item.
Extended the service url construction to include the service path.

[AFID-352] Unable to grab income records for Clients that do have income records

---

app/uk/gov/hmrc/taxhistory/model/api/Employment.scala
app/uk/gov/hmrc/taxhistory/model/nps/EmploymentStatus.scala
app/uk/gov/hmrc/taxhistory/services/EmploymentHistoryService.scala
test/uk/gov/hmrc/taxhistory/fixtures/Employments.scala
test/uk/gov/hmrc/taxhistory/services/EmploymentServiceSpec.scala

Generate dummy records to for periods where we have no record of an employment.

[AFID-363] View Employment for the full tax year - including 'no data' periods

---

app/uk/gov/hmrc/taxhistory/controllers/AllowanceController.scala
app/uk/gov/hmrc/taxhistory/package.scala
app/uk/gov/hmrc/taxhistory/services/EmploymentHistoryService.scala
test/uk/gov/hmrc/taxhistory/controllers/PayAndTaxControllerSpec.scala
test/uk/gov/hmrc/taxhistory/controllers/TaxAccountControllerSpec.scala
test/uk/gov/hmrc/taxhistory/services/AllowancesServiceSpec.scala
test/uk/gov/hmrc/taxhistory/services/EmploymentHistoryServiceSpec.scala
test/uk/gov/hmrc/taxhistory/services/PayAndTaxServiceSpec.scala
test/uk/gov/hmrc/taxhistory/services/TaxAccountServiceSpec.scala

Added current year behaviour, in line with existing front-end

[AFID-337] Current Year (CY) Income and Tax Record Summary Page

---

app/uk/gov/hmrc/taxhistory/controllers/StatePensionController.scala
app/uk/gov/hmrc/taxhistory/model/api/PayAsYouEarn.scala
app/uk/gov/hmrc/taxhistory/model/nps/IabdType.scala
app/uk/gov/hmrc/taxhistory/model/nps/StatePension.scala
app/uk/gov/hmrc/taxhistory/services/EmploymentHistoryService.scala
conf/app.routes
it/uk/gov/hmrc/taxhistory/services/TaxHistoryCacheServiceSpec.scala
test/resources/json/nps/response/iabds.json
test/uk/gov/hmrc/taxhistory/controllers/StatePensionControllerSpec.scala
test/uk/gov/hmrc/taxhistory/services/EmploymentHistoryServiceSpec.scala
test/uk/gov/hmrc/taxhistory/services/helper/EmploymentHistoryServiceHelperSpec.scala

Added new endpoint to retrieve state pension from cache.
Added functionality to seperate state pension fron iabds and build it as its own type.
Updated tests to include new functionality

[AFID-382] Added state pension functionality

---

app/Module.scala
app/uk/gov/hmrc/taxhistory/services/EmploymentHistoryService.scala
conf/application.conf
test/uk/gov/hmrc/taxhistory/services/EmploymentHistoryServiceSpec.scala
test/uk/gov/hmrc/taxhistory/utils/TestEmploymentHistoryService.scala

[AFID-433] added feature flag for state pension and job seekers allowance

[AFID-433] Feature flags

---

app/uk/gov/hmrc/taxhistory/services/EmploymentHistoryService.scala
conf/application.conf
test/uk/gov/hmrc/taxhistory/services/EmploymentHistoryServiceSpec.scala

[AFID-408] does not add filler employment when employment list is empty

[AFID-408] No employment records message

---

app/uk/gov/hmrc/taxhistory/services/SaAuthValidator.scala
test/uk/gov/hmrc/taxhistory/services/SaAuthServiceSpec.scala

APIS-4307 - Added digital handshake authorisation

---

build.sbt

##Update simple-reactivemongo for tax-history
I just updated simple-reactivemongo for tax-history So that the service compliant with latest bobby rulesimple-reactivemongo on a version that complies with bobby rules.
- Have you looked at the JIRA story to make sure all Acceptance Criteria has been met? Yes
- Have you done a visual check of the changes? Yes
- Is there any still commented or unused code? Lingering printlns? No
- Have things been implemented in a complicated way? N/a
- Are the test still over the coverage threshold? N/a
- Does the compiler throw a lot of warnings? No
- Have methods and tests been named clearly? N/a
- Were there any changes in the config? Do changes need to be made in app-config-??? N/a
- Have you done a manual walkthrough? Yes

DDCE-1170:Update simple-reactivemongo for tax-history

---

README.md
build.sbt
it/uk/gov/hmrc/taxhistory/services/TaxHistoryCacheServiceSpec.scala

Fix failing integration tests that were missed

[DP][DDCE-1344] Fix integration tests

---

build.sbt
project/build.properties
project/plugins.sbt

The sbt for the tax-history has been upgraded tax-history sbt version, So that it's up to the necessary version for play 2.6
- Have you looked at the JIRA story to make sure all Acceptance Criteria has been met? Yes
- Have you done a visual check of the changes? Yes
- Is there any still commented or unused code? Lingering printlns? No
- Have things been implemented in a complicated way? No
- Are the test still over the coverage threshold? Yes
- Does the compiler throw a lot of warnings? No
- Have methods and tests been named clearly? N/a
- Were there any changes in the config? Do changes need to be made in app-config-???  No
- Have you done a manual walkthrough? Yes

DDCE-1293: Sbt upgrade for tax-history

---

app/uk/gov/hmrc/taxhistory/config/AppConfig.scala
app/uk/gov/hmrc/taxhistory/controllers/TestOnlyController.scala
app/uk/gov/hmrc/taxhistory/services/TaxHistoryMongoCacheService.scala
conf/application.conf
it/uk/gov/hmrc/taxhistory/services/TaxHistoryCacheServiceSpec.scala
it/uk/gov/hmrc/taxhistory/services/TaxHistoryRepositoryServiceSpec.scala
project/AppDependencies.scala
project/plugins.sbt
run_all_tests.sh
test/uk/gov/hmrc/taxhistory/controllers/PayAsYouEarnControllerSpec.scala
test/uk/gov/hmrc/taxhistory/services/IabdsOpsSpec.scala
test/uk/gov/hmrc/taxhistory/services/helper/EmploymentHistoryServiceHelperSpec.scala

DDCE-2075 HMRC Mongo migration

---

run.sh

temp run.sh for correct AAC version

---

app/uk/gov/hmrc/taxhistory/connectors/ConnectorCorrelationId.scala
app/uk/gov/hmrc/taxhistory/connectors/ConnectorMetrics.scala
app/uk/gov/hmrc/taxhistory/connectors/DesNpsConnector.scala
app/uk/gov/hmrc/taxhistory/connectors/RtiConnector.scala
app/uk/gov/hmrc/taxhistory/services/EmploymentHistoryService.scala
conf/application.conf
test/uk/gov/hmrc/taxhistory/connectors/DesNpsConnectorSpec.scala
test/uk/gov/hmrc/taxhistory/connectors/RtiConnectorSpec.scala

DDCE-2562 :  Implement Correlation ID for IRV

---

project/AppDependencies.scala

DDCE-3226 - upgrades mongo versions

---

run.sh

DDCE-4513 Upgrade IRV to use SM2
